defaults: &defaults
  twitter_key: cHLNdPK4BPoXtghkowfjLw
  twitter_secret: snrURdBxphS3BOg4HK5ozBRzUThm6fGUTpwyG55NlSE
  secret_token: f62a63ed98ea795768053e15b4af4eb7081b4c1c2aca9ac46ca63c255a072f8674fd6532a731145e8946069ece073b6f083df6fd96fbe4bd7d2b9850cb0c81e3

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

preview:
  twitter_key: <%= ENV['TWITTER_KEY'] %>
  twitter_secret: <%= ENV['TWITTER_SECRET'] %>
  secret_token: <%= ENV['SECRET_TOKEN'] %>
