defaults: &defaults
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: db/development.sqlite3

test:
  <<: *defaults
  database: db/test.sqlite3

preview:
  <<: *defaults
  database: acid_preview

preview:
  adapter: postgresql
  encoding: utf8
  database: bu_preview
  pool: 5
  username: buktdev
  password: buktdev
  host: 127.0.0.1

production:
  <<: *defaults
  database: db/production.sqlite3
